### ISSUE TITLE
readability

### ISSUE THREAD

**Issue by ivargaphotoneo** [MiSo1289/sboptr#1]
Suggestion:
replace class definition with many booleans with more readable types
```
using my_pointer_type = sboptr::basic_sbo_ptr<
	interface,
	/* size of small buffer */ sizeof(void*) * 2,
	/* enable move */ true,
	/* enable copy */ true,
	/* enable heap storage */ true>;
```
replace with:
```
using my_pointer_type = sboptr::basic_sbo_ptr<
	interface,
	/* size of small buffer */ sizeof(void*) * 2,
	sboptr::movable, // sboptr::not_movable
	sboptr::copyable,
	sboptr::storage_heap; // sboptr::storage_stack
```

**Comment by MiSo1289** [comment]
I was thinking of maybe using a bitset.
```c++
using my_pointer_type = sboptr::basic_sbo_ptr<
	interface,
	/* size of small buffer */ sizeof(void*) * 2,
	sboptr::movable | sboptr::copyable | sboptr::allow_heap>;
```
Then you do not have to worry about order or naming disabled properties (no need for `not_movable`).
Using types in fixed parameter positions allows specialization, but here it does not matter, as I do all specialization on options in `detail::` where I can keep using bools.
Also, `allow_heap` is probably a better name than `storage_heap`, because stack storage is preferred even when heap is available; heap is used as a backup for types larger than `sbo_size`.
Another approach for the heap option is to take an allocator type parameter, and accept some special tag `never_allocate` to mean no allocations - but I'll probably start with the bit flag.
